setw -g mode-keys vi
bind -r r source-file ~/.config/tmux/tmux.conf

unbind-key -T copy-mode-vi v

bind-key -r f run-shell "tmux neww /usr/local/bin/tmux-sessionizer"
bind-key -T copy-mode-vi 'v' send -X begin-selection     
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  
bind-key -T copy-mode-vi 'y' send -X copy-selection      

bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R
